repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.1
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-lint
      - id: go-unit-tests
      - id: go-static-check # install https://staticcheck.io/docs/
#       - id: gofumpt # requires github.com/mvdan/gofumpt
#       - id: go-err-check # requires github.com/kisielk/errcheck
#       - id: golangci-lint # requires github.com/golangci/golangci-lint
#         args: [--config=.github/linters/.golangci.yml] # optional